version: "3"
services:
  jeed:
    image: "cs125/jeed:latest"
    ports:
      - "8888:8888"
    environment:
      - "SEMESTER=Testing"
      - "HTTP=http://0.0.0.0:8888"
      - "LIMITS_EXECUTION_TIMEOUT=1000"
      - "LIMITS_EXECUTION_MAXEXTRATHREADS=8"
